plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nextrace.app'
    compileSdk 36

    defaultConfig {
        applicationId "br.com.franmonteiro.nextrace"
        minSdk 24
        targetSdk 36
        versionCode 8
        versionName "1.4.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
}
